//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTIDE_Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class htmlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal htmlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTIDE_Web.htmlResource", typeof(htmlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] manual {
            get {
                object obj = ResourceManager.GetObject("manual", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;utf-8&quot;/&gt;
        ///&lt;title&gt;Quick Start&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///	ul{
        ///	list-style:none;
        ///	margin:0px;
        ///	padding:0px;
        ///	overflow:hidden;
        ///	}
        ///&lt;/style&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;Welcome to RT-IDE. To get started, please refer to the following.&lt;/p&gt;
        ///&lt;p&gt;If you require more detail please refer to the General Guide or User Manual&lt;/p&gt;
        ///&lt;h3&gt;New File&lt;/h3&gt;
        ///&lt;p&gt;To start making a new HTML page, click &quot;New File...&quot;. This will open the main editor.&lt;/p&gt;
        ///&lt;h3&gt;Open File&lt;/h3&gt;
        ///&lt;p&gt;To [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quickStart {
            get {
                return ResourceManager.GetString("quickStart", resourceCulture);
            }
        }
    }
}
